version: 3

tasks:
  default:
    cmds:
      - task: test
  silent: true

  test:
    depends:
      - build
    cmds:
      - go test -v ./encoding/bencoding
    method: none
    sources:
      - ./encoding/**/*.go
      - go.mod
    silent: true
    aliases:
      - t

  build:
    cmds:
      - go build -o ./bin/rssdd ./cmd/rssdd
      - go build -o ./bin/torrent-read ./cmd/torrent-read
    sources:
      - ./cmd/**/*.go
      - ./encoding/**/*.go
      - go.mod
      - go.sum
    silent: true
    aliases:
      - b

interval: 250ms
